# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains three jobs called "ehrWorkspace", "client" and "server"
  ehrWorkspace:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '18'
      - run: npm ci
        working-directory: ehr-workspace
      - run: npm run test
        working-directory: ehr-workspace
  client:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '18'
      - run: npm ci
        working-directory: client
      - run: npm run lint -- --no-fix
        working-directory: client
      #- run: npm run test
      #  working-directory: client
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # force npm to use https when checking out the ims-lti (and any other) git repos
      - run: git config --global url."https://github.com/".insteadOf ssh://git@github.com/
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '18'
      - run: npm ci
        working-directory: server
      - run: npm run lint -- --no-fix
        working-directory: server
      # run a subset of the tests avoiding those that require a database connection (i.e. *.server.spec.js)
      - run: npm run test:all:system
        working-directory: server
